# Modified by Draconic Evolution Render Patcher
# allowUnknownShaders can be set to true by Draconic Evolution Render Patcher to ensure proper rendering of Draconic Evolution entities.
# Draconic Evolution Render Patcher will override allowUnknownShaders value in this file to enable this feature.
# Disable this behavior in Draconic Evolution Render Patcher's config if undesired.

#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Feb 25 18:26:13 MSK 2026
allowUnknownShaders=true
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=0
shaderPack=BSL_v10.1.zip
