version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = true
endGatewayCulling = true
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
farmersdelight = true
extra_gauges = true
jeb_1_21_1 = true
storagedelight = true
golemoverhaul = true
dungeonsdelight = true
create_extra_casing = true
stellaris = true
copycats = true
mysticalagriculture = true
comforts = true
the_afterdark = true
create_enchantment_industry = true
create_sa = true
volex_vitality_crystals = true
mekanismgenerators = true
amendments = true
handcrafted = true
ftbquests = true
block_factorys_bosses = true
moonlight = true
sophisticatedbackpacks = true
treechop = true
mekanismadditions = true
endersdelight = true
cratedelight = true
supplementaries = true
l2complements = true
create = true
undead_revamp2 = true
deeperdarker = true
mekanism = true
endrem = true
createrailwaysnavigator = true
createcasing = true
createfisheryindustry = true
mythsandlegends = true
enigmaticlegacyplus = true
sereneseasons = true
nautec = true
minecraft = true
schematicenergistics = true
lootr = true
create_dragons_plus = true
fdlib = true
create_connected = true
fdbosses = true
merequester = true
createaddition = true
waystones = true
draconicevolution = true
aquaculturedelight = true
ae2 = true
duneons = true
createframed = true
dragonlib = true
monolib = true
computercraft = true
l2hostility = true
create_power_loader = true
